apiVersion: v1
kind: Service
metadata:
  name: tasky-service
  labels:
    app: tasky
  annotations:
    # Optional: Use this to request a Network Load Balancer (NLB) instead of CLB
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  selector:
    app: tasky     # Must match labels on your Deployment/Pod
  ports:
    - port: 80          # External port
      targetPort: 8080  # Container port
      protocol: TCP